version: '3.8'
services:
  api:
    build:
      context: ./app
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  ui:
    build:
      context: ./ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:5000/generate
    depends_on:
      - api